drop extension if exists "pg_net";


  create table "public"."historico_mensal" (
    "id" bigint generated by default as identity not null,
    "mes_ano" text,
    "faturamento" numeric(10,2),
    "lucro" numeric(10,2),
    "pecas_vendidas" integer,
    "created_at" timestamp with time zone default now()
      );



  create table "public"."pecas" (
    "id" bigint generated by default as identity not null,
    "legacy_id" bigint,
    "nome" text,
    "quantidade" integer,
    "preco_comprado_unitario" numeric(10,2),
    "preco_venda" numeric(10,2),
    "cor" text,
    "data_compra" date,
    "status" text,
    "data_venda" date,
    "tamanho" text,
    "created_at" timestamp with time zone default now(),
    "desconto" numeric,
    "lucro" numeric
      );



  create table "public"."usuarios" (
    "id" uuid not null default gen_random_uuid(),
    "email" text not null,
    "password_hash" text not null,
    "status" text default 'pending'::text,
    "created_at" timestamp with time zone default now()
      );


CREATE UNIQUE INDEX historico_mensal_mes_ano_key ON public.historico_mensal USING btree (mes_ano);

CREATE UNIQUE INDEX historico_mensal_pkey ON public.historico_mensal USING btree (id);

CREATE UNIQUE INDEX pecas_legacy_id_key ON public.pecas USING btree (legacy_id);

CREATE UNIQUE INDEX pecas_pkey ON public.pecas USING btree (id);

CREATE UNIQUE INDEX usuarios_email_key ON public.usuarios USING btree (email);

CREATE UNIQUE INDEX usuarios_pkey ON public.usuarios USING btree (id);

alter table "public"."historico_mensal" add constraint "historico_mensal_pkey" PRIMARY KEY using index "historico_mensal_pkey";

alter table "public"."pecas" add constraint "pecas_pkey" PRIMARY KEY using index "pecas_pkey";

alter table "public"."usuarios" add constraint "usuarios_pkey" PRIMARY KEY using index "usuarios_pkey";

alter table "public"."historico_mensal" add constraint "historico_mensal_mes_ano_key" UNIQUE using index "historico_mensal_mes_ano_key";

alter table "public"."pecas" add constraint "pecas_legacy_id_key" UNIQUE using index "pecas_legacy_id_key";

alter table "public"."usuarios" add constraint "usuarios_email_key" UNIQUE using index "usuarios_email_key";


